name: yts_movies
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^3.2.5
  cupertino_icons: ^0.1.3
  get_it: ^3.1.0
  injectable: ^0.2.2
  freezed: ^0.6.1
  dio: ^3.0.8
  retrofit: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  freezed_annotation: ^0.6.0
  injectable_generator: ^0.2.2
  retrofit_generator: ^1.3.0

flutter:
  uses-material-design: true
