name: yts_movies
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^3.2.5
  cupertino_icons: ^0.1.3
  get_it: ^3.1.0
  injectable: ^0.2.3
  dio: ^3.0.9
  retrofit: ^1.3.1+1
  pretty_dio_logger: ^1.1.0
  mobx: ^1.0.2
  flutter_mobx: ^1.0.1
  device_preview: ^0.3.0+1
  flutter_screenutil: ^1.0.2
  smooth_star_rating: ^1.0.4+2
  freezed_annotation: ^0.7.1
  transparent_image: ^1.0.0
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  freezed: ^0.8.2
  injectable_generator: ^0.2.4
  retrofit_generator: ^1.3.1+2
  mobx_codegen: ^1.0.2

flutter:
  uses-material-design: true
